#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/mt6879-common

PRODUCT_COPY_FILES += \
    vendor/motorola/mt6879-common/proprietary/product/etc/permissions/privapp-permissions-com.google.android.euicc.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-com.google.android.euicc.xml \
    vendor/motorola/mt6879-common/proprietary/system/etc/permissions/moto-telephony.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/moto-telephony.xml \
    vendor/motorola/mt6879-common/proprietary/system/etc/public.libraries-mtk.txt:$(TARGET_COPY_OUT_SYSTEM)/etc/public.libraries-mtk.txt \
    vendor/motorola/mt6879-common/proprietary/system_ext/etc/init/init.vtservice.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/init.vtservice.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/AbnormalDisplayLog_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/AbnormalDisplayLog_dynamic.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/MNL_Config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/MNL_Config.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/VideoLog_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/VideoLog_dynamic.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/aivrs.ini:$(TARGET_COPY_OUT_VENDOR)/etc/aivrs.ini \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/apdb/APDB_MT6879___W2408:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6879___W2408 \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/apdb/APDB_MT6879___W2408_ENUM:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6879___W2408_ENUM \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/ecc_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/ecc_list_OP01.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP01.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/ecc_list_OP02.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP02.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/ecc_list_OP09.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP09.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/ecc_list_OP12.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP12.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/ecc_list_OP17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP17.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/ecc_list_OP18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP18.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/ecc_list_OP20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP20.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/ecc_list_OP236.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP236.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/ecc_list_preference.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_preference.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/agps_profiles_conf2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/agps_profiles_conf2.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Bell_Mobility.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Bell_Mobility.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Blue_Wireless.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Blue_Wireless.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Boost_Mobile.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Boost_Mobile.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_C_Spire_NL.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_C_Spire_NL.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_C_Spire_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_C_Spire_US.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Carolina_West_Wireless.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Carolina_West_Wireless.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Dish.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Dish.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_FirstNet.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_FirstNet.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Inland_Cellular.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Inland_Cellular.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_MobileNation.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_MobileNation.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Movistar_Argentina.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Movistar_Argentina.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Movistar_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Movistar_Peru.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_NexTech_Ota.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_NexTech_Ota.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Nextel_Communications.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Nextel_Communications.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_No_Carrier_ID_LPP_Profile_11.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_No_Carrier_ID_LPP_Profile_11.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_No_Carrier_ID_LPP_Profile_7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_No_Carrier_ID_LPP_Profile_7.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_PTCI.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_PTCI.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Pine_Belt.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Pine_Belt.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_TELUS_Mobility.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_TELUS_Mobility.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_USC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_USC.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Virgin_Mobile.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Virgin_Mobile.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_nTelos.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_nTelos.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/hdrcfg_manaus.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/hdrcfg_manaus.cfg \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init.insmod.mt6879.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/init.insmod.mt6879.cfg \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/android.hardware.drm@1.4-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.4-service.widevine.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/android.hardware.gnss-service.mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss-service.mediatek.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/android.hardware.neuralnetworks-shim-service-mtk.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks-shim-service-mtk.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/android.hardware.security.keymint-service.trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service.trustonic.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/hw/init.mmi.backup.trustlet.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.mmi.backup.trustlet.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/init.bip_ap.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bip_ap.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/init.bt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bt_drv.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/init.cccimdinit.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccimdinit.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/init.cccirpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccirpcd.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/init.connfem.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.connfem.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/init.conninfra.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.conninfra.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/init.gps_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps_drv.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/init.gps_pwr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps_pwr.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/init.vtservice_hidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vtservice_hidl.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/init.wlan_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wlan_drv.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/lbs_hidl_service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/lbs_hidl_service.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/mtk_agpsd_p.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_agpsd_p.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/mtkrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtkrild.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/muxreport.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/muxreport.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/nvram_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nvram_daemon.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/tee.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tee.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/tetheroffloadservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tetheroffloadservice.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/vendor.mediatek.hardware.mmagent@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mmagent@1.1-service.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/vendor.mediatek.hardware.nwk_opt@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.nwk_opt@1.0-service.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/vendor.mmi.carrier.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mmi.carrier.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/vendor.mmi.cxp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mmi.cxp.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/vendor.trustonic.tee@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.trustonic.tee@1.1-service.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/volte_clientapi_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/volte_clientapi_ua.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/init/wlan_assistant.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wlan_assistant.rc \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/meow.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/meow.cfg \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/mot_spn_table:$(TARGET_COPY_OUT_VENDOR)/etc/mot_spn_table \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/motorola/sensors/mot_sensor_settings.json:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/sensors/mot_sensor_settings.json \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/mpe.conf:$(TARGET_COPY_OUT_VENDOR)/etc/mpe.conf \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/mtk_platform_codecs_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mtk_platform_codecs_config.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/nnapi_powerhal.json:$(TARGET_COPY_OUT_VENDOR)/etc/nnapi_powerhal.json \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/permissions/com.mediatek.hardware.vow_dsp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.mediatek.hardware.vow_dsp.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/slp_conf:$(TARGET_COPY_OUT_VENDOR)/etc/slp_conf \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/smartpa_param/AW_DSP.bin:$(TARGET_COPY_OUT_VENDOR)/etc/smartpa_param/AW_DSP.bin \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/smsdbvisitor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/smsdbvisitor.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/special_pws_channel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/special_pws_channel.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/vendor-apns-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vendor-apns-conf.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/virtual-spn-conf-by-efgid1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efgid1.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/virtual-spn-conf-by-efpnn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efpnn.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/virtual-spn-conf-by-efspn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efspn.xml \
    vendor/motorola/mt6879-common/proprietary/vendor/etc/virtual-spn-conf-by-imsi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-imsi.xml

PRODUCT_PACKAGES += \
    APUWareApusysServer \
    APUWareHmpServer \
    APUWareUtilsServer \
    AVCSecureVdecCA \
    HEVCSecureVdecCA \
    VP9SecureVdecCA \
    libGLES_meow \
    libMEOW_data \
    libMEOW_gift \
    libMEOW_qt \
    libMEOW_trace \
    libGLES_mali \
    android.hardware.gnss-impl-mediatek \
    android.hardware.gnss@2.1-impl-mediatek \
    audio.r_submix.mediatek \
    gps.default \
    gralloc.default \
    hwcomposer.mtk_common \
    kmsetkey.trustonic \
    libMcGatekeeper \
    libSoftGatekeeper \
    android.hardware.graphics.allocator@4.0-impl-mediatek \
    android.hardware.graphics.mapper@4.0-impl-mediatek \
    gralloc.common \
    vendor.mediatek.hardware.pq@2.15-impl \
    vulkan.mali \
    sensors.mediatek.V2.0 \
    sound_trigger.primary.default \
    vendor.mediatek.hardware.bluetooth.audio@2.2-impl \
    vendor.mediatek.hardware.keymaster_attestation@1.1-impl \
    vendor.mediatek.hardware.mms@1.6-impl \
    vendor.mediatek.hardware.nvram@1.1-impl \
    vendor.mediatek.hardware.videotelephony@1.0-impl \
    lbs_hidl_service-impl \
    libAVCSecureVencCA \
    libDefaultFpsActor \
    libFrameRecord \
    libJpgEncPipe \
    libMcClient \
    libMtkAinrEnh \
    libMtkSpeechEnh \
    libMtkSpeechEnh_swb \
    libNoFpsActor \
    libOpenCL \
    libTEECommon \
    lib_iir \
    libaal_key \
    libadropbox \
    libalsautils-v31 \
    libapmonitor_vendor \
    libappgamepq \
    libapu_mdw \
    libapu_mdw_batch \
    libapusys \
    libapusys_edma \
    libarmnn \
    libarmnn_ndk.mtk.vndk \
    libasn1c_core \
    libasn1c_mapi \
    libasn1c_mdmi \
    libaudiocompensationfilter_vendor \
    libaudiocompensationfilterc \
    libaudiocomponentengine_vendor \
    libaudiocomponentenginec \
    libaudiocustparam_vendor \
    libaudiodcrflt_vendor \
    libaudiofmtconv \
    libaudioloudc \
    libaudioprimarydevicehalifclient \
    libaudiosmartpamtk \
    libaudiotoolkit_vendor \
    libaurisysdemo \
    libawinicsmartpaparse \
    libbessound_hd_mtk_vendor \
    libblisrc32_vendor \
    libbluetooth_audio_session_mediatek \
    libbluetooth_hw_test \
    libbluetooth_mtk \
    libbluetooth_mtk_pure \
    libbluetooth_relayer \
    libbluetoothem_mtk \
    libbt-vendor \
    libbwc \
    libcapctrl \
    libcares_naptr \
    libcarrierconfig \
    libccci_util \
    libcmdl \
    libcmdl_ndk.mtk.vndk \
    libcodec2_mtk_c2store \
    libcodec2_mtk_vdec \
    libcodec2_mtk_venc \
    libcodec2_vpp_qt_plugin \
    libcodec2_vpp_rs_plugin \
    libcomposer_ext \
    libconnfem \
    libcustom_nvram \
    libcvsd_mtk \
    libdecrypt \
    libdre \
    libfile_op \
    libforkexecwrap \
    libformatter \
    libged \
    libgpu_aux \
    libgpud \
    libgralloc_extra \
    libgralloc_metadata \
    libgralloctypes_mtk \
    libgwsd-ril \
    libgwsdv2-ril \
    libgwsdv3-ril \
    libgz_gp_client \
    libgz_uree \
    libhdrvideo \
    libhfmanager \
    libhfmanagerwrapper \
    libhwm \
    libifcutils_mtk \
    libion_mtk \
    libion_ulit \
    libipsec_ims_shr \
    libjpeg-alpha-oal_vendor \
    libjpeg-alpha_vendor \
    libkmsetkey \
    libksensor \
    libladder \
    libmipc \
    libmmagent \
    libmml \
    libmmprofile \
    libmnetlink_v104 \
    libmsbc_mtk \
    libmtk-ril \
    libmtk-rilop \
    libmtkares \
    libmtkconfig \
    libmtkconfigutils \
    libmtkcutils \
    libmtkhardware_legacy \
    libmtklimiter_vendor \
    libmtkmipc-ril \
    libmtkmipc-rilop \
    libmtknetcap \
    libmtknetutils \
    libmtkproperty \
    libmtkrillog \
    libmtkrilutils \
    libmtkshifter_vendor \
    libmtkspparser \
    libmtkspparser_swb \
    libmtksysutils \
    libmtktinyxml \
    libmtkutils \
    libmvpu_cic_ci_compiler \
    libmvpu_clc_cl_compiler \
    libmvpu_clc_mvpu_debuginfo \
    libmvpu_clc_mvpu_elf \
    libmvpu_clc_mvpu_utility \
    libmvpu_clc_vpu_isa \
    libmvpu_config \
    libmvpu_engine \
    libmvpu_engine_pub \
    libmvpu_pattern \
    libmvpu_pattern_pub \
    libmvpu_runtime \
    libmvpu_runtime_pub \
    libmvpuop_mtk_cv \
    libmvpuop_mtk_nn \
    libneuroeara \
    libneuron_graph_delegate.mtk_vendor \
    libneuropilot_hal_utils \
    libnir_neon_driver_ndk.mtk.vndk_vendor \
    libnpagent \
    libnpagent_server \
    libnvram \
    libnvram_sec \
    libnwk_opt_halwrap_vendor \
    liboemcrypto \
    libpixelflinger \
    libpqframework \
    libratconfig \
    librgbwlightsensor \
    librilfusion \
    librpc \
    librt_extamp_intf \
    libsimlock \
    libsimmelock \
    libspeech_enh_lib \
    libspeechparser_vendor \
    libstorage_otp \
    libsysenv \
    libtflite_mtk_vendor \
    libthha \
    libtinyxml2-v31 \
    libtlcWidevineModularDrm \
    libtrm \
    libudf \
    liburee_meta_drmkeyinstall \
    libvcodec_oal \
    libvcodecdrv_header_stub \
    libvia-ril \
    libviagpsrpc \
    libviamipc-ril \
    libwifi-hal-mtk \
    libwifitest \
    libwpfa \
    libwvhidl \
    libmockdrmcryptoplugin \
    libwvdrmengine \
    meta_wifi_data \
    motrilutils \
    arm.graphics-V1-ndk_platform \
    libDR \
    libaiselector \
    libdpframework \
    libmnl \
    libmtk_drvb \
    libneuralnetworks_sl_driver_mtk_prebuilt \
    libneuron_adapter_mgvi \
    libneuron_runtime.5 \
    libneuron_wrapper \
    libnir_neon_driver \
    libpq_cust_base \
    libpq_prot \
    libpqparamparser \
    libpqpconfig \
    nwk_opt_imp \
    sensors.moto \
    vendor.mediatek.hardware.apmonitor@2.0 \
    vendor.mediatek.hardware.apuware.apusys@2.0_vendor \
    vendor.mediatek.hardware.apuware.apusys@2.1_vendor \
    vendor.mediatek.hardware.apuware.hmp@1.0_vendor \
    vendor.mediatek.hardware.apuware.utils@2.0_vendor \
    vendor.mediatek.hardware.audio@6.1 \
    vendor.mediatek.hardware.audio@7.1 \
    vendor.mediatek.hardware.clientapi@1.0 \
    vendor.mediatek.hardware.composer_ext@1.0 \
    vendor.mediatek.hardware.keymaster_attestation@1.0 \
    vendor.mediatek.hardware.keymaster_attestation@1.1 \
    vendor.mediatek.hardware.lbs@1.0 \
    vendor.mediatek.hardware.mdmonitor@1.0 \
    vendor.mediatek.hardware.mmagent@1.0 \
    vendor.mediatek.hardware.mmagent@1.1 \
    vendor.mediatek.hardware.mms@1.0 \
    vendor.mediatek.hardware.mms@1.1 \
    vendor.mediatek.hardware.mms@1.2 \
    vendor.mediatek.hardware.mms@1.3 \
    vendor.mediatek.hardware.mms@1.4 \
    vendor.mediatek.hardware.mms@1.5 \
    vendor.mediatek.hardware.mms@1.6 \
    vendor.mediatek.hardware.mtkradioex@2.0 \
    vendor.mediatek.hardware.mtkradioex@3.0 \
    vendor.mediatek.hardware.netdagent@1.0 \
    vendor.mediatek.hardware.neuropilot.agent@1.0 \
    vendor.mediatek.hardware.neuropilot.agent@1.1 \
    vendor.mediatek.hardware.neuropilot.agent@1.2 \
    vendor.mediatek.hardware.nvram@1.0 \
    vendor.mediatek.hardware.nvram@1.1 \
    vendor.mediatek.hardware.nwk_opt@1.0 \
    vendor.mediatek.hardware.power@1.1 \
    vendor.mediatek.hardware.power@2.0 \
    vendor.mediatek.hardware.pq@2.0 \
    vendor.mediatek.hardware.pq@2.1 \
    vendor.mediatek.hardware.pq@2.10 \
    vendor.mediatek.hardware.pq@2.11 \
    vendor.mediatek.hardware.pq@2.12 \
    vendor.mediatek.hardware.pq@2.13 \
    vendor.mediatek.hardware.pq@2.14 \
    vendor.mediatek.hardware.pq@2.15 \
    vendor.mediatek.hardware.pq@2.2 \
    vendor.mediatek.hardware.pq@2.3 \
    vendor.mediatek.hardware.pq@2.4 \
    vendor.mediatek.hardware.pq@2.5 \
    vendor.mediatek.hardware.pq@2.6 \
    vendor.mediatek.hardware.pq@2.7 \
    vendor.mediatek.hardware.pq@2.8 \
    vendor.mediatek.hardware.pq@2.9 \
    vendor.mediatek.hardware.radio_op@3.0 \
    vendor.mediatek.hardware.videotelephony@1.0_vendor \
    vendor.trustonic.tee.tui@1.0 \
    vendor.trustonic.tee@1.0 \
    vendor.trustonic.tee@1.1 \
    libapuwareapusys.mtk \
    libapuwareapusys_v2.mtk \
    libapuwarehmp.mtk \
    libapuwareutils.mtk \
    libapuwareutils_v2.mtk \
    libapuwarexrp.mtk \
    libapuwarexrp_v2.mtk \
    libarmnn_ndk.mtk \
    libcmdl_ndk.mtk \
    libcomutils \
    libimsma \
    libimsma_adapt \
    libimsma_rtp \
    libimsma_socketwrapper \
    libmtk_vt_service \
    libmtk_vt_wrapper \
    libmvpu_cic_ci_compiler.mtk \
    libmvpu_cic_ci_compiler_25.mtk \
    libmvpu_clc_14_mvpu_debuginfo_25.mtk \
    libmvpu_clc_14_mvpu_elf_25.mtk \
    libmvpu_clc_14_mvpu_utility_25.mtk \
    libmvpu_clc_mvpu_debuginfo.mtk \
    libmvpu_clc_mvpu_elf.mtk \
    libmvpu_clc_mvpu_utility.mtk \
    libmvpu_config.mtk \
    libmvpu_engine.mtk \
    libmvpu_engine_25.mtk \
    libmvpu_engine_25_pub.mtk \
    libmvpu_engine_pub.mtk \
    libmvpu_pattern.mtk \
    libmvpu_pattern_25.mtk \
    libmvpu_pattern_25_pub.mtk \
    libmvpu_pattern_pub.mtk \
    libmvpu_runtime.mtk \
    libmvpu_runtime_25.mtk \
    libmvpu_runtime_25_pub.mtk \
    libmvpu_runtime_builtin.mtk \
    libmvpu_runtime_builtin_25.mtk \
    libmvpu_runtime_pub.mtk \
    libmvpuop25_mtk_cv.mtk \
    libmvpuop25_mtk_nn.mtk \
    libmvpuop_mtk_cv.mtk \
    libmvpuop_mtk_nn.mtk \
    libneuron_graph_delegate.mtk \
    libneuronusdk_adapter.mtk \
    libnir_neon_driver_ndk.mtk \
    libsignal \
    libsink-mtk \
    libsource \
    libtflite_mtk.mtk \
    libtflite_mtk \
    libvcodec_cap \
    libvcodec_capenc \
    libvt_avsync \
    vendor.mediatek.hardware.apuware.apusys-V5-ndk \
    vendor.mediatek.hardware.apuware.apusys@1.0 \
    vendor.mediatek.hardware.apuware.apusys@2.0 \
    vendor.mediatek.hardware.apuware.apusys@2.1 \
    vendor.mediatek.hardware.apuware.hmp@1.0 \
    vendor.mediatek.hardware.apuware.utils-V1-ndk \
    vendor.mediatek.hardware.apuware.utils@1.0 \
    vendor.mediatek.hardware.apuware.utils@2.0 \
    vendor.mediatek.hardware.apuware.xrp-V1-ndk \
    vendor.mediatek.hardware.apuware.xrp@1.0 \
    vendor.mediatek.hardware.apuware.xrp@2.0 \
    vendor.mediatek.hardware.videotelephony-V1-ndk \
    vendor.mediatek.hardware.videotelephony@1.0 \
    EuiccPartnerApp \
    EuiccGoogle \
    ImsService \
    MtkGbaService \
    moto-telephony \
    mediatek-ims-base \
    mediatek-ims-oem-plugin \
    android.hardware.neuralnetworks-shim-service-mtk.xml \
    android.hardware.security.keymint-service.trustonic.xml \
    android.hardware.security.secureclock-service.trustonic.xml \
    android.hardware.security.sharedsecret-service.trustonic.xml \
    gnss-mtk-default.xml \
    gnss-mtk@2.1-service.xml \
    lbs_hidl_service@1.0.xml \
    manifest_android.hardware.drm@1.4-service.widevine.xml \
    manifest_apuware_apusys.xml \
    manifest_apuware_hmp.xml \
    manifest_apuware_utils.xml \
    manifest_hwcomposer.xml \
    vendor.mediatek.hardware.neuropilot.agent@1.0-service.xml \
    bip_ap \
    ccci_mdinit \
    ccci_rpcd \
    conninfra_loader \
    hardware_revisions \
    android.hardware.drm@1.4-service.widevine \
    android.hardware.gnss-service.mediatek \
    android.hardware.neuralnetworks-shim-service-mtk \
    android.hardware.security.keymint-service.trustonic \
    android.hardware.graphics.allocator@4.0-service-mediatek.mt6879 \
    mtkfusionrild \
    tetheroffloadservice \
    vendor.mediatek.hardware.keymaster_attestation@1.1-service \
    vendor.mediatek.hardware.mmagent@1.1-service \
    vendor.mediatek.hardware.mms@1.6-service \
    vendor.mediatek.hardware.nvram@1.1-service \
    vendor.mediatek.hardware.nwk_opt@1.0-service \
    vendor.mediatek.hardware.pq@2.2-service \
    vendor.trustonic.tee@1.1-service \
    vtservice_hidl \
    init.insmod \
    init.mmi.backup.trustlet \
    init.mmi.block_perm \
    init.mmi.boot \
    init.mmi.shutdown \
    init.mmi.touch \
    lbs_hidl_service \
    mcDriverDaemon \
    mnld \
    motobox \
    mtk_agpsd \
    muxreport \
    nvram_daemon \
    vendor.mmi.cxp \
    volte_clientapi_ua \
    wlan_assistant \
    wmt_launcher \
    wmt_loader \
    vtservice

PRODUCT_PACKAGES += \
    vendor_bin_hw_android_hardware_graphics_allocator@4_0-service-mediatek \
    vendor_bin_expat \
    vendor_lib64_egl_libGLES_mali_so \
    vendor_lib64_hw_audio_r_submix_mt6879_so \
    vendor_lib64_hw_kmsetkey_default_so \
    vendor_lib64_hw_gatekeeper_trustonic_so \
    vendor_lib64_hw_gatekeeper_default_so \
    vendor_lib64_hw_android_hardware_graphics_allocator@4_0-impl-mediatek_so \
    vendor_lib64_hw_android_hardware_graphics_mapper@4_0-impl-mediatek_so \
    vendor_lib64_hw_gralloc_common_so \
    vendor_lib64_hw_vendor_mediatek_hardware_pq@2_15-impl_so \
    vendor_lib64_hw_vulkan_mali_so \
    vendor_lib64_hw_sensors_mt6879_so \
    vendor_lib64_arm_graphics-V1-ndk_platform_so \
    vendor_lib64_libDR_so \
    vendor_lib64_libaiselector_so \
    vendor_lib64_libdpframework_so \
    vendor_lib64_libmnl_so \
    vendor_lib64_libmtk_drvb_so \
    vendor_lib64_libneuralnetworks_sl_driver_mtk_prebuilt_so \
    vendor_lib64_libneuron_adapter_mgvi_so \
    vendor_lib64_libneuron_runtime_5_so \
    vendor_lib64_libneuron_wrapper_so \
    vendor_lib64_libnir_neon_driver_so \
    vendor_lib64_libpq_cust_base_so \
    vendor_lib64_libpq_prot_so \
    vendor_lib64_libpqparamparser_so \
    vendor_lib64_libpqpconfig_so
